INSERT INTO cars (name, make, model, mp3_file_name, category, origin_country, decade) VALUES
('BMW M3 E46', 'BMW', 'M3 E46', '/static/audio/bmw_m3_e46.wav', 'Sports Sedan', 'Germany', '2000s'),
('Ferrari 458', 'Ferrari', '458', '/static/audio/ferrari_458.wav', 'Supercar', 'Italy', '2010s'),
('Lamborghini Huracan', 'Lamborghini', 'Huracan', '/static/audio/lamborghini_huracan.wav', 'Supercar', 'Italy', '2010s'),
('Porsche 911 GT3', 'Porsche', '911 GT3', '/static/audio/porsche_911_gt3.wav', 'Sports Car', 'Germany', '2010s'),
('Audi R8 V10', 'Audi', 'R8 V10', '/static/audio/audi_r8_v10.wav', 'Supercar', 'Germany', '2010s'),
('McLaren 720S', 'McLaren', '720S', '/static/audio/mclaren_720s.wav', 'Supercar', 'United Kingdom', '2010s'),
('Nissan GT-R R35', 'Nissan', 'GT-R R35', '/static/audio/nissan_gtr_r35.wav', 'Sports Car', 'Japan', '2000s'),
('Toyota Supra MK4', 'Toyota', 'Supra MK4', '/static/audio/toyota_supra_mk4.wav', 'Sports Car', 'Japan', '1990s'),
('Honda NSX', 'Honda', 'NSX', '/static/audio/honda_nsx.wav', 'Sports Car', 'Japan', '1990s'),
('Chevrolet Corvette C8', 'Chevrolet', 'Corvette C8', '/static/audio/chevrolet_corvette_c8.wav', 'Sports Car', 'United States', '2020s'),
('Ford Mustang GT', 'Ford', 'Mustang GT', '/static/audio/ford_mustang_gt.wav', 'Muscle Car', 'United States', '2010s'),
('Dodge Challenger Hellcat', 'Dodge', 'Challenger Hellcat', '/static/audio/dodge_challenger_hellcat.wav', 'Muscle Car', 'United States', '2010s'),
('Mercedes-AMG GT63S', 'Mercedes-AMG', 'GT63S', '/static/audio/mercedes_amg_gt63s.wav', 'Grand Tourer', 'Germany', '2020s'),
('Aston Martin DB11', 'Aston Martin', 'DB11', '/static/audio/aston_martin_db11.wav', 'Grand Tourer', 'United Kingdom', '2010s'),
('Bugatti Chiron', 'Bugatti', 'Chiron', '/static/audio/bugatti_chiron.wav', 'Hypercar', 'France', '2010s'),
('Koenigsegg Agera RS', 'Koenigsegg', 'Agera RS', '/static/audio/koenigsegg_agera_rs.wav', 'Hypercar', 'Sweden', '2010s'),
('Pagani Huayra', 'Pagani', 'Huayra', '/static/audio/pagani_huayra.wav', 'Hypercar', 'Italy', '2010s'),
('Lotus Exige', 'Lotus', 'Exige', '/static/audio/lotus_exige.wav', 'Sports Car', 'United Kingdom', '2000s'),
('Alfa Romeo Giulia Quadrifoglio', 'Alfa Romeo', 'Giulia Quadrifoglio', '/static/audio/alfa_romeo_giulia_quadrifoglio.wav', 'Sports Sedan', 'Italy', '2010s'),
('Subaru WRX STI', 'Subaru', 'WRX STI', '/static/audio/subaru_wrx_sti.wav', 'Rally Car', 'Japan', '2000s');
